from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from fastapi.middleware.cors import CORSMiddleware
from pydub import AudioSegment
from pathlib import Path
from nbclient import NotebookClient
import json
import tempfile
import os

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],  # Adjust this to match your frontend URL
    allow_credentials=True,
    allow_methods=["*"],  # Allow all HTTP methods
    allow_headers=["*"],  # Allow all headers
)
# Mount the static directory to serve the HTML frontend and other static files
app.mount("/static", StaticFiles(directory="static"), name="static")

# Serve the index.html file at the root URL
@app.get("/")
async def get_index():
    return FileResponse(os.path.join("static", "index.html"))

@app.post("/crossfade/")
async def crossfade_audio(
    file1: UploadFile = File(...),
    file2: UploadFile = File(...),
    duration: int = 3000  # Crossfade duration in milliseconds
):
    # Load files into temporary files
    with tempfile.NamedTemporaryFile(delete=False, suffix=".mp3") as tmp1, \
         tempfile.NamedTemporaryFile(delete=False, suffix=".mp3") as tmp2:
        tmp1.write(await file1.read())
        tmp2.write(await file2.read())
        tmp1_path = tmp1.name
        tmp2_path = tmp2.name

    # Load audio segments
    audio1 = AudioSegment.from_file(tmp1_path)
    audio2 = AudioSegment.from_file(tmp2_path)

    # Perform crossfade
    crossfaded_audio = audio1.append(audio2, crossfade=duration)

    # Save the result to a temporary file
    with tempfile.NamedTemporaryFile(delete=False, suffix=".mp3") as output:
        crossfaded_path = output.name
        crossfaded_audio.export(crossfaded_path, format="mp3")

    # Clean up the temporary input files
    os.remove(tmp1_path)
    os.remove(tmp2_path)

    # Return the crossfaded file as response
    return FileResponse(crossfaded_path, media_type="audio/mpeg", filename="crossfaded.mp3")

NOTEBOOK_PATH = "content/notebook.ipynb"  # Input notebook
MP3_FILE_PATH = "content/fullPlaylist.mp3"  # Path to the MP3 file generated by the notebook

@app.post("/run-notebook")
async def run_notebook():
    try:
        # Load and execute the notebook
        with open(NOTEBOOK_PATH, "r", encoding="utf-8") as f:
            notebook_content = json.load(f)

        client = NotebookClient(notebook_content)
        client.execute()

        # Check if the MP3 file exists
        if not os.path.exists(MP3_FILE_PATH):
            raise HTTPException(status_code=500, detail="MP3 file not found after notebook execution.")

        # Return the MP3 file as a response
        return FileResponse(
            MP3_FILE_PATH,
            media_type="audio/mpeg",
            filename=MP3_FILE_PATH
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Notebook execution failed or MP3 retrieval failed: {str(e)}")